In [9]:
import numpy as np

python_list = [1, 2, 3, 4, 5]
numpy_array = np.array(python_list)
print(numpy_array)

[1 2 3 4 5]


In [10]:
oned_shape = numpy_array.shape
oned_size = numpy_array.size
oned_type = numpy_array.dtype

In [11]:
print('1D NumPy Array:')
print('Array:', numpy_array)
print(f'Shape: {oned_shape}')
print(f'Size: {oned_size}')
print(f'DataType: {oned_type}')

1D NumPy Array:
Array: [1 2 3 4 5]
Shape: (5,)
Size: 5
DataType: int64


In [14]:
print('1D numpy Array:')
print('Array:', numpy_array)
print('Shape:', oned_shape)
print('Size:', oned_size)
print('DataType:', oned_type)

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 4, 6, 8])

addition = arr1 + arr2
print(addition)


1D numpy Array:
Array: [1 2 3 4 5]
Shape: (5,)
Size: 5
DataType: int64
[12 24 36 48]


In [15]:
subtraction = arr1 - arr2
print(subtraction)


[ 8 16 24 32]


In [16]:
multiplication = arr1 * arr2
print(multiplication)
print(multiplication.dtype)


[ 20  80 180 320]
int64


In [17]:
division = arr1 / arr2
print(division)
print(division.dtype)


[5. 5. 5. 5.]
float64


In [18]:
data = np.array([85,90,78,92,88,85,95])

data_mean = np.mean(data)
data_median = np.median(data)
data_std = np.std(data)     
data_variance = np.var(data)
data_range = np.max(data) - np.min(data)


In [19]:
print(f'mean: {data_mean}')
print(f'median: {data_median}')
print(f'standard deviation: {data_std}')
print(f'variance: {data_variance}') 
print(f'range: {data_range}')


mean: 87.57142857142857
median: 88.0
standard deviation: 5.150787536377128
variance: 26.53061224489796
range: 17


In [20]:
sliced_array = numpy_array[0:3]

index_condition = numpy_array > 3
index_codition_array = numpy_array[numpy_array > 3]


In [21]:
print('Sliced Array:', sliced_array)
print('OG Array:', numpy_array)
print('Array_based_on_condition:', index_condition)
print(index_codition_array)


Sliced Array: [1 2 3]
OG Array: [1 2 3 4 5]
Array_based_on_condition: [False False False  True  True]
[4 5]


In [22]:
combined_result = numpy_array[1:4][numpy_array[1:4] > 3]
print('OG Array:', numpy_array)
print('Combined Array:', combined_result)


OG Array: [1 2 3 4 5]
Combined Array: [4]


In [24]:
temp_data = np.array([22.3, 23.1, 24.5, 25.8, 23.6, 26.7, 27.9, 29.2, 30.5, 24.7, 23.4, 22.1, 25.3, 26.4, 28.7, 29.8, 31.2, 32.4, 30.7, 29.5, 27.8, 26.6])
mean_temp = np.mean(temp_data)
median_temp = np.median(temp_data)
std_dev_temp = np.std(temp_data)

print(f'mean: {mean_temp}')
print(f'median: {median_temp}')
print(f'standard deviation: {std_dev_temp}')


mean: 26.918181818181814
median: 26.65
standard deviation: 3.0013082546898477


In [25]:
temp_in_f = (temp_data * 9/5) + 32
print(temp_in_f)


[72.14 73.58 76.1  78.44 74.48 80.06 82.22 84.56 86.9  76.46 74.12 71.78
 77.54 79.52 83.66 85.64 88.16 90.32 87.26 85.1  82.04 79.88]


In [26]:
hot_days = temp_data[temp_data > 30]
print('Hot Temp Days:', hot_days)
print('Num of Hot Days:', len(hot_days))


Hot Temp Days: [30.5 31.2 32.4 30.7]
Num of Hot Days: 4


In [27]:
base_temp = 20
cooling_degrees_total = np.sum(np.maximum(0, base_temp - temp_data))
print('Cooling Degrees:', cooling_degrees_total)


Cooling Degrees: 0.0
